django_d4/accounts/urls.py
from django.urls import path
from .views import SignUp


urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
]

django_d4/django_d4/urls.py
from django.contrib import admin
from django.urls import path, include
from simpleapp.views import multiply, ProductsList
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from rest_framework import routers
from simpleapp import views


router = routers.DefaultRouter()
router.register(r'product', views.ProductViewset)
router.register(r'category', views.CategoryViewset)
# router.register(r'subscriptions', views.SubscriptionsViewset)


urlpatterns = [
    # path(r'^', include('polls.urls')), admin/
    path('', ProductsList.as_view(), name='product_list'),
    path('admin/', admin.site.urls),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}), name='swagger-ui'),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('products/', include('simpleapp.urls')),
    path('multiply/', multiply),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include('accounts.urls')),  # Добавил
    path('accounts/', include('allauth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]
# urlpatterns += i18n_patterns(
#     path('', include('basic.urls'))
# )

django_d4/simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.cache import cache
from django.utils.translation import gettext as _, pgettext_lazy
# from django.utils.translation import
# импортируем «ленивый» геттекст с подсказкой


# Товар для витрины
class Product(models.Model):
    """
    Класс Product, отображает товары и имеет обязательные поля name,
    description, quantity,
    category, price.
    """
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0,
                                      'Quantity should be >= 0')])
    # Поле которое будет ссылаться на модель категории
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE,
                                 related_name='products',
                                 verbose_name=pgettext_lazy(
                                     'help text for Product model',
                                     'This is the help text'))
    # все продукты в категории будут доступны через поле products
    price = models.FloatField(
        validators=[MinValueValidator(0.0,
                                      'Price should be >= 0')])

    @property
    def on_stock(self):
        """
         Отображает есть ли товар на складе есть=True, нет=False
        """
        return self.quantity > 0

    def __str__(self):
        return (f'{self.category} : {self.name} : {self.quantity} :'
                f' {self.description[:20]}')

    # Добавим absolute_urls
    def get_absolute_url(self):
        return f'/products/{self.id}'  # products
        # return reverse('product_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'product-{self.pk}')


# Категория, к которой будет привязываться товар
class Category(models.Model):
    """
    Класс Category отображает категорию товара, name с максимальной
    длиной 100 символов.
    """
    name = models.CharField(max_length=100, unique=True,
                            help_text=_('category name'))  # добавим
    # переводящийся текст подсказку к полю

    def __str__(self):
        return f'{self.name.title()}'


class Subscriptions(models.Model):
    """
    Класс Подписчиков имеет два поля
    user = models.ForeignKey to=User,
    category = models.ForeignKey to=Category.
    """
    user = models.ForeignKey(to=User, on_delete=models.CASCADE,
                             related_name='subscriptions')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE,
                                 related_name='subscriptions')

django_d4/templates/product.html
{% extends 'flatpages/default.html' %}

{% block title %}
Product
{% endblock title %}

<!--В контенте на странице выводим сам товар, идентификатор которого -->
<!--был передан в url-->
{% block content %}
<h1>product.html</h1>
    <h2>{{ product }}</h2>

    <h1>Один продукт</h1>
    <hr>
{% endblock content %}

django_d4/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
    <hr>
    <form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete"/>
    </form>
{% endblock content %}

django_d4/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

django_d4/templates/products.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
<!--Подключаем новый файл с нашим тегом-->
{% load custom_tags %}


{% block title %}
Products
{% endblock title %}}


{% block content %}
    <hr>
    <h3>products.html</h3>
    <hr>
    <h1>Все товары</h1>
<!--Вот так выглядело использование переменной и фильтра-->
<!--    {# <h3>{{ time_now|date:'M d Y'}}</h3> #}-->
<!--А вот так мы используем наш тег-->
    <h3>{% current_time '%b %d %Y' %}</h3>

<!--        Если в переменной next_sale будет NONE,
то выведется указанный в переменной текст-->
        {# <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}</h3> #}

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
    <form action="" method="get">
        {# Переменная которую передали через контекст, может сгенерировать нам форму с полями #}
        {{ filterset.form.as_p }}
        {# Добавим кнопку отправки данных формы #}
        <input type="submit" value="Найти" />
    </form>

    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
{% if perms.simpleapp.add_product %}
     <a href="{% url 'product_create' %}">Добавить товар</a>
{% endif %}
  <hr>
        {% if products %}
            <table>
                 <tr>
                    <td>Название</td>
                    <td>Описание</td>
                    <td>Категория</td>
                    <td>Цена</td>
                    <td>Количество</td>
                 {# Условие получается составным #}
                 {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
                    <td>Действие</td>
                 {% endif %}
                </tr>
                {% for product in products %}
                <tr>
                    <td>
                        <a href="{% url 'product_detail' pk=product.id %}">{{ product.name }}</a>
                    </td>
                    <td>{{ product.description|truncatewords:2}}</td>
                    <td>{{ product.category.name }}</td>
                    <td>{{ product.price|currency:"rub" }}</td>
                    <td>{{ product.quantity }}</td>

                    <td>
                        {# А здесь доступ к каждой ссылке будет проверяться отдельно #}
                        {% if perms.simpleapp.change_product %}
                            <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                        {% endif %}
                        {% if perms.simpleapp.delete_product %}
                            <a href="{% url 'product_delete' pk=product.id %}">Удалить</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        {% else %}
            <h2>Товаров нет!</h2>
        {% endif %}
        {# Добавим пагинацию на страницу #}
        {# Информация о предыдущих страницах #}
        {% if page_obj.has_previous %}
            {# <a href="?page=1">1</a> # было #}
            {# Стало #}
            <a href="?{% url_replace page=1 %}">1</a>

            {% if page_obj.previous_page_number != 1 %}
                ...
                {# Было  #}
            {# <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a> #}
                {# Стало #}
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {# Информация о текущей странице #}
        {{ page_obj.number }}

        {# Информация о следующих страницах #}
        {% if page_obj.has_next %}
            {# Было  #}
            {# <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a> #}
            {# Стало #}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>

            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                {# Было  #}
                {# <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a> #}
                {# Стало #}
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}


{% endblock content %}

django_d4/templates/products_form.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
<h2>{% block title %}
    Products_Forms
    {% endblock title %}}</h2>
{% block content %}
    <hr>
    <h3>products_forms.html</h3>
    <hr>
    <h3>{% current_time '%b %d %Y' %}</h3>
    <form action="" method="get">
        {{ filterset.form.non_field_errors }}
        {{ filterset.form.name__icontains.errors }}
        <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
        <input
            id="{{ filterset.form.name__icontains.id }}"
            name="{{ filterset.form.name__icontains.name }}"
            value="{{ filterset.form.name__icontains.value }}"
            class="form-control"
            >
        <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
    <hr>
        {% if products %}
            <table>
                 <tr>
                    <td>Название</td>
                    <td>Описание</td>
                    <td>Категория</td>
                    <td>Цена</td>
                    <td>Количество</td>
                </tr>
                {% for product in products %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description|truncatewords:2 }}</td>
                    <td>{{ product.category.name }}</td>
                    <td>{{ product.price|currency:"rub" }}</td>
                    <td>{{ product.quantity }}</td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <h2>Товаров нет!</h2>
        {% endif %}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}
        {{ page_obj.number }}
        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
{% endblock content %}

django_d4/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id"
                       value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action"
                            value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

django_d4/templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta
charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "//lms-cdn.skillfactory" +
           ".ru/assets/courseware/v1/a084991b3a1596be3ed570c65c56393c/asset-v1:SkillFactory+FPW-2.0+27AUG2020+type@asset+block/openapi-schema.yaml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>

django_d4/templates/translation.html
{% load i18n %}
{% load tz %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Перевод</title>
    <style>
        body {background-color: {% if current_time.hour >= 19 or current_time.hour <= 7 %} darkcyan {% else %} powderblue {% endif %};}
    </style>

</head>
<body>
<h1>{% trans "Check out my new cool translation" %}!</h1>

    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %}
        <input type="hidden" name="next" value="{{ redirect_to }}">
            {% get_current_language as LANGUAGE_CODE %}
            <select name="language" id="">

            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}

                {% for language in languages %}
                    <option value="{{ language.code }}"
                            {% if language.code == LANGUAGE_CODE %} selected
                            {% endif %}>
                        {{ language.name_local }} - {{ language.code }}
                    </option>
                {% endfor %}
             </select>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %}selected
            {% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }}

        {% for model in models %}
        <div class="model-class">
            {{ model.name }}
            {{ model.category }}
            {{ model.description }}
        </div>
        {% endfor %}
</body>
</html>